# Understanding Pandas Series and DataFrames - Lab

# Introduction

In this lab, let's get some hands on practice working with data cleanup using Pandas.

## Objectives
You will be able to:

* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
df = pd.read_csv('turnstile_180901.txt')
print(len(df))
df.head()

197625

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

# Practice

## Objectives
You will be able to:
* Understand and explain what Pandas Series and DataFrames are and how they differ from dictionaries and lists
* Create Series & DataFrames from dictionaries and lists
* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

# Rename all the columns to lower case

In [20]:
df.columns = df.columns.str.lower()

# Change the Index to be the Line Names

In [21]:
df = df.set_index('linename')

# Painstakingly change the index back

In [22]:
#????

## Create another column 'Num_Lines' that is a count of how many lines pass through a station. Then sort your dataframe by this column in descending order.

In [23]:
number_of_lines = []
number_of_lines = list(map(lambda dfcell: len(dfcell), df.index))
number_of_lines
df = df.assign(Num_Lines=number_of_lines)
#len(df.index[0])

df.sort_values(by='Num_Lines', ascending=False)

,c/a,unit,scp,station,division,date,time,desc,entries,exits,Num_Lines
linename,,,,,,,,,,,
1237ACENQRSW,R151,R033,00-00-00,TIMES SQ-42 ST,IRT,08/30/2018,00:00:00,REGULAR,1417952,3267016,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/29/2018,16:00:00,REGULAR,2836145,3311412,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/27/2018,16:00:00,REGULAR,2830710,3305818,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/27/2018,20:00:00,REGULAR,2832048,3306310,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/28/2018,00:00:00,REGULAR,2832325,3306433,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/28/2018,04:00:00,REGULAR,2832359,3306438,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/28/2018,08:00:00,REGULAR,2832561,3306716,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/28/2018,09:57:08,REGULAR,2832815,3307705,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/28/2018,12:00:00,REGULAR,2832994,3308064,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/28/2018,16:00:00,REGULAR,2833390,3308536,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/28/2018,20:00:00,REGULAR,2834686,3309190,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/29/2018,00:00:00,REGULAR,2835069,3309328,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/29/2018,04:00:00,REGULAR,2835109,3309348,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/29/2018,08:00:00,REGULAR,2835310,3309579,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/29/2018,12:00:00,REGULAR,2835721,3310943,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/29/2018,20:00:00,REGULAR,2837390,3312091,12
ACENQRS1237W,A021,R032,01-00-02,TIMES SQ-42 ST,BMT,08/25/2018,04:00:00,REGULAR,1965089,1942027,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/30/2018,00:00:00,REGULAR,2837721,3312246,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/30/2018,04:00:00,REGULAR,2837752,3312261,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/30/2018,08:00:00,REGULAR,2837924,3312478,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/30/2018,08:49:06,REGULAR,2838018,3312826,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/30/2018,12:00:00,REGULAR,2838332,3313701,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/30/2018,16:00:00,REGULAR,2838767,3314206,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/30/2018,20:00:00,REGULAR,2839999,3314879,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/31/2018,00:00:00,REGULAR,2840336,3315042,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/31/2018,04:00:00,REGULAR,2840375,3315061,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/31/2018,08:00:00,REGULAR,2840537,3315242,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/31/2018,12:00:00,REGULAR,2840895,3316295,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/31/2018,16:00:00,REGULAR,2841591,3316775,12
ACENQRS1237W,A021,R032,01-00-01,TIMES SQ-42 ST,BMT,08/31/2018,20:00:00,REGULAR,2842280,3317347,12
...,...,...,...,...,...,...,...,...,...,...,...
1,PTH04,R551,00-04-04,GROVE STREET,PTH,08/29/2018,03:54:11,REGULAR,53064,30905,1
1,PTH04,R551,00-04-04,GROVE STREET,PTH,08/28/2018,23:42:11,REGULAR,53064,30893,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/26/2018,04:04:23,REGULAR,28064,12480,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/26/2018,08:16:23,REGULAR,28074,12483,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/26/2018,12:28:23,REGULAR,28151,12494,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/26/2018,16:40:23,REGULAR,28229,12514,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/30/2018,17:16:23,REGULAR,32803,13807,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/30/2018,13:04:23,REGULAR,32726,13762,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/30/2018,08:52:23,REGULAR,32358,13726,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/30/2018,04:40:23,REGULAR,31911,13640,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/30/2018,00:28:23,REGULAR,31908,13639,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/29/2018,20:16:23,REGULAR,31883,13597,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/29/2018,16:04:23,REGULAR,31682,13414,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/29/2018,11:52:23,REGULAR,31616,13390,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/29/2018,07:40:23,REGULAR,31045,13260,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/29/2018,03:28:23,REGULAR,30850,13245,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/28/2018,23:16:23,REGULAR,30844,13237,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/28/2018,19:04:23,REGULAR,30744,13164,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/28/2018,14:52:23,REGULAR,30507,13036,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/28/2018,10:40:23,REGULAR,30358,13013,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/28/2018,06:28:23,REGULAR,29534,12894,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/28/2018,02:16:23,REGULAR,29500,12893,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/27/2018,22:04:23,REGULAR,29490,12881,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/27/2018,17:52:23,REGULAR,29332,12754,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/27/2018,13:40:23,REGULAR,29168,12698,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/27/2018,09:28:23,REGULAR,28975,12659,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/27/2018,05:16:23,REGULAR,28319,12541,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/27/2018,01:04:23,REGULAR,28318,12541,1
1,PTH04,R551,00-04-05,GROVE STREET,PTH,08/26/2018,20:52:23,REGULAR,28305,12531,1
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,RIT,08/31/2018,21:00:00,REGULAR,5554,348,1

## Write a function to clean a column name.

In [24]:
def clean(col_name):
    cleaned = col_name.title()
    return cleaned

In [25]:
#This is a list comprehension. It applies your clean function to every item in the list.
#We then reassign that to df.columns
#You shouldn't have to change anything here.
#Your function above should work appropriately here.
df.columns = [clean(col) for col in df.columns]

In [46]:
#Checking the output, we can see the results.
df.columns
df = df.rename(columns={'Exits                                                               ' : 'Exits'})
df.columns

Index(['C/A', 'Unit', 'Scp', 'Station', 'Division', 'Date', 'Time', 'Desc',
       'Entries', 'Exits', 'Num_Lines'],
      dtype='object')

## Compare subway traffic by day of the week. Display this as a graph.

In [47]:
df.Date = pd.to_datetime(df.Date)

In [48]:
df_by_Date = df.sort_values(by='Date', ascending=True)
df_by_Date

,C/A,Unit,Scp,Station,Division,Date,Time,Desc,Entries,Exits,Num_Lines
linename,,,,,,,,,,,
NQR456W,A002,R051,02-00-00,59 ST,BMT,2018-08-25,00:00:00,REGULAR,6736067,2283184,7
FG,N542,R241,00-06-00,15 ST-PROSPECT,IND,2018-08-25,04:30:00,REGULAR,117886561,361570,2
FG,N542,R241,00-06-00,15 ST-PROSPECT,IND,2018-08-25,08:30:00,REGULAR,117886574,361583,2
FG,N542,R241,00-06-00,15 ST-PROSPECT,IND,2018-08-25,12:30:00,REGULAR,117886678,361613,2
D,E014,R374,00-05-00,BAY PKWY,BMT,2018-08-25,21:00:00,REGULAR,150995591,0,1
D,E014,R374,00-05-00,BAY PKWY,BMT,2018-08-25,17:00:00,REGULAR,150995591,0,1
D,E014,R374,00-05-00,BAY PKWY,BMT,2018-08-25,13:00:00,REGULAR,150995591,0,1
D,E014,R374,00-05-00,BAY PKWY,BMT,2018-08-25,09:00:00,REGULAR,150995591,0,1
D,E014,R374,00-05-00,BAY PKWY,BMT,2018-08-25,05:00:00,REGULAR,150995591,0,1
D,E014,R374,00-05-00,BAY PKWY,BMT,2018-08-25,01:00:00,REGULAR,150995591,0,1
FG,N542,R241,00-06-00,15 ST-PROSPECT,IND,2018-08-25,16:30:00,REGULAR,117886762,361668,2
FG,N542,R241,00-06-00,15 ST-PROSPECT,IND,2018-08-25,20:30:00,REGULAR,117886844,361743,2
7,R532H,R328,02-05-01,METS-WILLETS PT,IRT,2018-08-25,17:00:00,REGULAR,1,504,1
7,R532H,R328,02-05-01,METS-WILLETS PT,IRT,2018-08-25,13:00:00,REGULAR,1,504,1
7,R532H,R328,02-05-01,METS-WILLETS PT,IRT,2018-08-25,09:00:00,REGULAR,1,504,1
FG,N542,R241,00-06-00,15 ST-PROSPECT,IND,2018-08-25,00:30:00,REGULAR,117886560,361555,2
7,R532H,R328,02-05-01,METS-WILLETS PT,IRT,2018-08-25,05:00:00,REGULAR,1,504,1
FG,N542,R241,00-06-01,15 ST-PROSPECT,IND,2018-08-25,00:30:00,REGULAR,5940297,1949042,2
FG,N542,R241,00-06-01,15 ST-PROSPECT,IND,2018-08-25,04:30:00,REGULAR,5940302,1949075,2
FG,N542,R241,00-06-01,15 ST-PROSPECT,IND,2018-08-25,08:30:00,REGULAR,5940341,1949098,2
FG,N542,R241,00-06-01,15 ST-PROSPECT,IND,2018-08-25,12:30:00,REGULAR,5940540,1949144,2
FG,N542,R241,00-06-01,15 ST-PROSPECT,IND,2018-08-25,16:30:00,REGULAR,5940690,1949205,2
FG,N542,R241,00-06-01,15 ST-PROSPECT,IND,2018-08-25,20:30:00,REGULAR,5940817,1949308,2
FG,N543,R289,00-00-00,FT HAMILTON PKY,IND,2018-08-25,01:00:00,REGULAR,4699496,1000865,2
FG,N543,R289,00-00-00,FT HAMILTON PKY,IND,2018-08-25,05:00:00,REGULAR,4699501,1000875,2
FG,N543,R289,00-00-00,FT HAMILTON PKY,IND,2018-08-25,09:00:00,REGULAR,4699577,1000887,2
FG,N543,R289,00-00-00,FT HAMILTON PKY,IND,2018-08-25,13:00:00,REGULAR,4699790,1000907,2
FG,N543,R289,00-00-00,FT HAMILTON PKY,IND,2018-08-25,17:00:00,REGULAR,4699989,1000946,2
FG,N543,R289,00-00-00,FT HAMILTON PKY,IND,2018-08-25,21:00:00,REGULAR,4700160,1000985,2
D,E014,R374,00-00-04,BAY PKWY,BMT,2018-08-25,21:00:00,REGULAR,1974154,857429,1
...,...,...,...,...,...,...,...,...,...,...,...
1,PTH12,R542,00-04-01,TWENTY THIRD ST,PTH,2018-08-31,05:54:23,REGULAR,32880,599640,1
1,PTH12,R542,00-04-01,TWENTY THIRD ST,PTH,2018-08-31,10:06:23,REGULAR,32880,599640,1
1,PTH12,R542,00-04-01,TWENTY THIRD ST,PTH,2018-08-31,14:18:23,REGULAR,32880,599640,1
1,PTH12,R542,00-00-04,TWENTY THIRD ST,PTH,2018-08-31,20:28:40,REGULAR,2387039,223129,1
1,PTH12,R542,00-00-02,TWENTY THIRD ST,PTH,2018-08-31,11:58:50,REGULAR,505525,9974,1
1,PTH12,R542,00-00-02,TWENTY THIRD ST,PTH,2018-08-31,07:46:50,REGULAR,505392,9969,1
1,PTH12,R542,00-00-02,TWENTY THIRD ST,PTH,2018-08-31,03:34:50,REGULAR,505364,9966,1
1,PTH11,R545,00-04-04,14TH STREET,PTH,2018-08-31,06:06:10,REGULAR,10600,546478,1
1,PTH11,R545,00-04-04,14TH STREET,PTH,2018-08-31,10:32:10,REGULAR,10603,547255,1
1,PTH11,R545,00-04-04,14TH STREET,PTH,2018-08-31,14:44:10,REGULAR,10608,547514,1
1,PTH11,R545,00-04-04,14TH STREET,PTH,2018-08-31,18:56:10,REGULAR,10628,547822,1
1,PTH11,R545,00-04-04,14TH STREET,PTH,2018-08-31,23:08:10,REGULAR,10638,547972,1
1,PTH11,R545,00-04-05,14TH STREET,PTH,2018-08-31,02:21:51,REGULAR,331,19657,1
1,PTH11,R545,00-04-05,14TH STREET,PTH,2018-08-31,06:33:51,REGULAR,337,19748,1
1,PTH11,R545,00-04-05,14TH STREET,PTH,2018-08-31,10:46:22,REGULAR,337,20575,1
1,PTH11,R545,00-04-05,14TH STREET,PTH,2018-08-31,14:58:22,REGULAR,337,20907,1
1,PTH11,R545,00-04-05,14TH STREET,PTH,2018-08-31,19:10:22,REGULAR,350,21256,1
1,PTH11,R545,00-04-05,14TH STREET,PTH,2018-08-31,23:22:22,REGULAR,352,21385,1
1,PTH12,R542,00-00-00,TWENTY THIRD ST,PTH,2018-08-31,03:40:36,REGULAR,49351,3255,1
1,PTH12,R542,00-00-00,TWENTY THIRD ST,PTH,2018-08-31,07:52:36,REGULAR,49352,3259,1
1,PTH12,R542,00-00-00,TWENTY THIRD ST,PTH,2018-08-31,12:04:36,REGULAR,49357,3261,1
1,PTH12,R542,00-00-00,TWENTY THIRD ST,PTH,2018-08-31,16:16:36,REGULAR,49391,3265,1
1,PTH12,R542,00-00-00,TWENTY THIRD ST,PTH,2018-08-31,20:28:36,REGULAR,49451,3268,1
1,PTH12,R542,00-00-01,TWENTY THIRD ST,PTH,2018-08-31,03:37:23,REGULAR,1123519,16056,1
1,PTH12,R542,00-00-01,TWENTY THIRD ST,PTH,2018-08-31,07:49:23,REGULAR,1123539,16057,1
1,PTH12,R542,00-00-01,TWENTY THIRD ST,PTH,2018-08-31,12:01:23,REGULAR,1123615,16060,1
1,PTH12,R542,00-00-01,TWENTY THIRD ST,PTH,2018-08-31,16:13:23,REGULAR,1123966,16062,1
1,PTH12,R542,00-00-01,TWENTY THIRD ST,PTH,2018-08-31,20:25:23,REGULAR,1124437,16066,1
1,PTH13,R541,00-04-07,THIRTY ST,PTH,2018-08-31,16:24:07,REGULAR,1,287451,1
R,TRAM2,R469,00-05-01,RIT-ROOSEVELT,RIT,2018-08-31,21:00:00,REGULAR,5554,348,1

In [49]:
dates = []
dates = list(filter(lambda dfcell: dfcell, df_by_Date.Date))
dates

[Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),
 Timestamp('2018-08-25 00:00:00'),

In [ ]:
num_of_rows = int(df_by_Date.Entries.count())
index = list(range(num_of_rows))
traffic = []
for i in index:
    traffic.append(df_by_Date.Entries[i] + df_by_Date.Exits[i])
traffic

## Is there more subway traffic on a weekend or a weekday?    Be specific in comparing magnitudes.

In [ ]:
#Your code here

# Drop a couple of columns

In [ ]:
# Your code here